---
- name: Fail if no accounts are specified
  fail:
    msg: Variable mutt_accounts is empty
  when: mutt_accounts == []

- name: Install necessary programs
  become: True
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - neomutt
    - isync

- name: Create necessary dirs
  file:
    path: "{{ item }}"
    recurse: yes
    state: directory
  with_items:
    - ~/.config/neomutt
    - ~/.mail
    - ~/.config/systemd/user

- name: Configure neomutt
  template:
    src: "{{ item }}.j2"
    dest: "~/.config/neomutt/{{ item }}"
  with_items:
    - neomuttrc

- name: Configure mail accounts for neomutt
  template:
    src: account.j2
    dest: "~/.config/neomutt/account.{{ item.name }}"
  with_items:
    - "{{ mutt_accounts }}"

- name: Configure signatures for neomutt
  template:
    src: signature.j2
    dest: "~/.config/neomutt/signature.{{ item.name }}"
  with_items:
    - "{{ mutt_accounts }}"

- name: Configure mbsync
  template:
    src: mbsyncrc.j2
    dest: ~/.mbsyncrc

- name: Configure mbsync service
  template:
    src: "systemd/mbsync.{{ item }}.j2"
    dest: "~/.config/systemd/user/mbsync.{{ item }}"
  with_items:
    - service
    - timer

- name: Enable mbsync timer
  systemd:
    user: yes
    name: mbsync.timer
    state: started
    enabled: yes
